### DISCUSSION TITLE
How to load CSS files as asset/resource?

### DISCUSSION THREAD

**Discussion by tlaziuk** [web-infra-dev/rspack#8981] [Q&A]
Hey, I would like to load a `css` file as a resource, but with additional applying the "default" css loader (experiments.css) on it while bundling - or at least something close to it, so:
```ts
import resourceUrl from './style.css';

// should output the url of the css file
console.log(resourceUrl);
```

So far I have the following rule:
```ts
{
  test: [/\.css$/],
  use: [
    {
      loader: 'builtin:lightningcss-loader',
    },
  ],
  type: 'asset/resource',
},
```

It almost works. Almost because I get the URL of the CSS file, but the file itself is not being "loaded" (url and @import rules are not transformed):
```css
/* lightningcss transformed the file, but rspack didn't parse the imports further */
@font-face{font-family:Tiempos Fine;font-style:normal;font-display:swap;src:url(./tiempos-fine-light.woff2)format("woff2")}
```

How do I make it so the CSS file gets parsed?
