### ISSUE TITLE
[Bug Report]: sass module imports in CRA-TS example doesn't style components

### ISSUE THREAD

**Issue by Mctalian** [web-infra-dev/rspack#2338]
### System Info

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 850.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.1
  npmPackages:
    @rspack/cli: workspace:* => 0.1.1
    
Running from commit [0f0969a25752c033ed33a1b3ed15c90bfdf3db4a](https://github.com/web-infra-dev/rspack/commit/0f0969a25752c033ed33a1b3ed15c90bfdf3db4a)

### Details

When importing styles from a sass module in a React component, rspack throws javascript errors.

rspack.conf.js

```javascript
const CopyPlugin = require('copy-webpack-plugin');
/*
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
  entry: {
    main: './src/index.tsx'
  },
  module: {
    rules: [
      {
        test: /\.svg$/,
        type: 'asset/resource'
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'sass-loader'
          }
        ],
        type: "css"
      }
    ]
  },
  builtins: {
    html: [{
      template: './index.html'
    }],
    css: {
      modules: {
        localsConvention: 'camelCaseOnly'
      }
    }
  },
  plugins: [new CopyPlugin([{
    from: "public",
    to: "."
  }])]
}
```

App.css renamed to App.module.scss and casing changed on classes:

```scss
.app {
  text-align: center;
}

.app-logo {
  height: 40vmin;
  pointer-events: none;
}

@media (prefers-reduced-motion: no-preference) {
  .app-logo {
    animation: app-logo-spin infinite 20s linear;
  }
}

.app-header {
  background-color: #282c34;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
}

.app-link {
  color: #61dafb;
}

@keyframes app-logo-spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

App.tsx updated to import styles from sass module and use them in className attributes:

```tsx
import React from 'react';
import logo from './logo.svg';
import { app, appHeader, appLogo, appLink } from './App.module.scss';


function App() {
  return (
    <div className={app}>
      <header className={appHeader}>
        <img src={logo} className={appLogo} alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className={appLink}
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;

```

You can see the unstyled page behind and the devTools window shows no classes.
![image](https://user-images.githubusercontent.com/5081281/226062905-d9a04710-e7e6-48dd-9107-63b5e6789ea6.png)

### Reproduce Steps

1. Set up rspack repo following guidelines in CONTRIBUTING.md
2. Rename `examples/cra-ts/src/App.css` to `examples/cra-ts/src/App.scss` Change `examples/cra-ts/rspack.conf.js`, `examples/cra-ts/src/App.tsx`, and `examples/cra-ts/src/App.scss` to match the details above.
3. Run `pnpm --filter ./examples/cra-ts run dev` from the repo root.
