### ISSUE TITLE
[Bug Report]: wrong css url when ~ in the middle of url

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#2424]
### System Info

/

### Details

```css
.a { a: url(http://xxx.xx/img~img.png) }
```

css url will resolve `img.png` instead of `http://xxx.xx/img~img.png`

### Reproduce Steps

/
