### ISSUE TITLE
nightly release

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#2484]
Auto releases a new version daily, allowing developers to get bug fixes quickly, rather than delaying up to a week before a package that fixes issues.

**Comment by Boshen** [comment]
I'm going to try and refactor our release workflow using [GitHub reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) next week. cc @h-a-n-a

**Comment by Boshen** [comment]
For builds, I want to define a target matrix in the caller workflow:

```
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
```

The callee reusable workflow will take these targets as inputs and make the correct build.
It seems that I need to defined a mapping from the target to configs.
