### ISSUE TITLE
[Bug Report]:  panic when handle css contains calc

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#2595]
### System Info

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.95 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/71636_1680514176616/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/71636_1680514176616/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox Developer Edition: 111.0
    Safari: 15.6.1
  npmPackages:
    @rspack/cli: workspace:* => 0.1.4 

### Details

![image](https://user-images.githubusercontent.com/17974631/229479522-c386e89b-7894-4434-a89c-e62aa6e586e1.png)

when i removes calc from css the panic disappear
```css
.App-header {
  background-color: #282c34;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
}
```

### Reproduce Steps

```
cd examples/cra && pnpm build
```
