### ISSUE TITLE
Allow to config skip resolve protocol in css

### ISSUE THREAD

**Issue by jerrykingxyz** [web-infra-dev/rspack#2976]
### What problem does this feature solve?

expect skip resolve when use some custom protocol

example: 
``` css
@import "my_protocol://path"

.test {
  background: url("my_protocol://img")
}
```

### What does the proposed API of configuration look like?

1. Add a new field in `builtins` or `resolve` to config the skip resolve list
2. Change `externals` behavior when matching css
