### ISSUE TITLE
css output is broken when `:global` is specified in the css selector.

### ISSUE THREAD

**Issue by Thiry1** [web-infra-dev/rspack#3611]
### System Info

 System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 76.59 MB / 24.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.19 - ~/.nodebrew/current/bin/yarn
    npm: 9.5.1 - ~/.nodebrew/current/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5
  npmPackages:
    @rspack/cli: ^0.2.3 => 0.2.3 

### Details

When build the following scss, the css output is broken.
input: 
```scss
.my-class:global {
  font-size: 100px;
}
```
output:
```css
 {
  font-size: 100px;
}
```
As you can see, the selector is missing. But js has the selector correctly.
https://github.com/Thiry1/rspack-bug-repro/blob/main/rspack-dist/main.js#L13

However, putting a space between the selector and `:global` seems to work.
input: 
```scss
.my-class :global {
  font-size: 100px;
}
```
output:
```css
.b2fabca1ec7065ff  {
  font-size: 100px;
}
```

I don't know if not putting a space between the selector and :global is a valid syntax, but webpack is able to output it with no problem.

### Reproduce link

https://github.com/Thiry1/rspack-bug-repro

### Reproduce Steps

1. run `npm run build`
2. see `rspack-dist` directory.

**Comment by hyf0** [comment]
@ahabhgk Do we support patterns like this?

```css
.my-class:global {
  font-size: 100px;
}
```
