### ISSUE TITLE
[scss + css modules]Attribute selector disappears when using `:global` with Parent Selector

### ISSUE THREAD

**Issue by Thiry1** [web-infra-dev/rspack#3777]
### System Info

  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 41.41 MB / 24.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.20.1 - ~/.nodebrew/current/bin/node
    Yarn: 3.6.1 - ~/.nodebrew/current/bin/yarn
    npm: 8.19.4 - ~/.nodebrew/current/bin/npm
    pnpm: 8.6.6 - ~/.nodebrew/current/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5

### Details

When build the following scss, the css output is broken.Attribute selector disappears.
input:
```scss
.class:global {
  &[data-x="true"] {
    > .inner {
      color: red;
    }
  }
  &[data-x="false"] {
    > .inner {
      color: green;
    }
  }
  > .inner {
    color: blue;
  }
}
```
output:
```scss
._460b8fe177c56095d0be > .inner {
  color: red;
}
._460b8fe177c56095d0be > .inner {
  color: green;
}
._460b8fe177c56095d0be > .inner {
  color: blue;
}
```

However, the following scss builds correctly.

```scss
.class[data-x="true"]:global {
  > .inner {
    color: red;
  }
}
.class[data-x="false"]:global {
  > .inner {
    color: green;
  }
}
.class:global {
  > .inner {
    color: blue;
  }
}
```

I used dart-sass to compile the first input code into css. Here is the output.
```css
.class:global[data-x=true] > .inner {
  color: red;
}
.class:global[data-x=false] > .inner {
  color: green;
}
.class:global > .inner {
  color: blue;
}
```

It seems that swc_css is not handling codes like `.class:global[data-x=true] ` correctly.
So I added some tests to swc_css.I confirmed swc_css is not handling codes like `.class:global[data-x=true] ` correctly.
https://github.com/thiry1/swc/commit/6d814fc43b34f9e9cb01f5246307eca663b41d37

I don't know whether rspack or swc_css should be modified. What do you think?

### Reproduce link

https://github.com/Thiry1/rspack-bug-repro/tree/scss-atribute-selector

### Reproduce Steps

1. run `npm run build`
2. see `./rspack-dist/main.css` (you can see webpack's output on ./webpack-dist/main.css)
