### ISSUE TITLE
How to handle invalid `@import` statement in wrong order.

### ISSUE THREAD

**Issue by hyf0** [web-infra-dev/rspack#403]
# Summary

> In CSS 2.1, any `@import` rules must precede all other rules (except the `@charset` rule, if present).  [link](https://stackoverflow.com/questions/9860763/css-import-and-the-order-of-it)
- esbuild chooses to generate invalid code with warnings.
- webapck chooses to be tolerated and tries to generate correct output.

input:

![image](https://user-images.githubusercontent.com/49502170/174709903-dfdb7b38-68ee-43b1-a5b5-92a7a18af5ab.png)

# webpack output

```css
@import url(https://some/other/external/css);
@import url(https://some/external/css);
.c {
  background: red;
}

.c {
  color: yellow;
}

body {
  background: red;
}

.b {
  background: red;
}

.b {
  color: yellow;
}
```

# esbuild output

```css
/* src/import/c.css */
.c {
  background: red;
}
@import url(https://some/other/external/css);
.c {
  color: yellow;
}

/* src/import/a.css */
body {
  background: red;
}

/* src/import/b.css */
.b {
  background: red;
}
@import url(https://some/external/css);
.b {
  color: yellow;
}

```

with warning

```
▲ [WARNING] All "@import" rules must come first [invalid-@import]

    src/import/b.css:5:0:
      5 │ @import url("https://some/external/css");
        ╵ ~~~~~~~

  This rule cannot come before an "@import" rule

    src/import/b.css:1:0:
      1 │ .b {
        ╵ ^

▲ [WARNING] All "@import" rules must come first [invalid-@import]

    src/import/c.css:5:0:
      5 │ @import url("https://some/other/external/css");
        ╵ ~~~~~~~

  This rule cannot come before an "@import" rule

    src/import/c.css:1:0:
      1 │ .c {
        ╵ ^
```
