### ISSUE TITLE
@rspack/plugin-react-refresh tried to access react-refresh

### ISSUE THREAD

**Issue by HrvojeFER** [web-infra-dev/rspack#4284]
### System Info

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 5.66 GB / 15.95 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.47)
    Internet Explorer: 11.0.22621.1

### Details

Running `yarn rspack --mode production build` gave me:

```
Error: @rspack/plugin-react-refresh tried to access react-refresh (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

I solved the problem adding the following to `yarnrc.yml`:

```yaml
packageExtensions:
  "@rspack/plugin-react-refresh@0.3.6":
    dependencies:
      react-refresh: ">=0.10.0 <1.0.0"
```

Please consider making `react-refresh` a dependency of `@rspack/plugin-react-refresh` and not a peer dependency.

### Reproduce Steps

1. init repo with yarn pnp
2. `yarn install @rspack/cli`
3. create simple `rspack.config.js`
4. `yarn rspack --mode production build`
