### ISSUE TITLE
How to ignore absolute paths in url()

### ISSUE THREAD

**Issue by noyobo** [web-infra-dev/rspack#4518]
```css
.logo {
  background-image: url("/images/logo.png");
}
```

I expect that resources starting with `/` are not bundled when used explicitly. How do I configure this?

In my project, these paths starting with `/` are copied to outputPath , so I hope to skip the compilation of such files.

```
error[internal]: Failed to resolve /images/logo.png in css/auto|/xxx/node_modules/less-loader/dist/cjs.js!/xxxx/src/pages/home/index.module.less
```
