### ISSUE TITLE
`url(...)` in css variables does not transformed correctly

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack#4605]
```css
body {
  --abc: url(...)
}
```

**Actual**
The result feeds back the original content. 

**Expected**
Should be transformed and included in the asset
