### ISSUE TITLE
rspack.SwcCssMinimizerRspackPlugin generated wrong css content

### ISSUE THREAD

**Issue by guomio** [web-infra-dev/rspack#5196]
### System Info

```sh
System:
    OS: Linux 6.2 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC 7763 64-Core Processor
    Memory: 5.20 GB / 7.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/nvm/current/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.3 - ~/nvm/current/bin/npm
    pnpm: 8.11.0 - ~/nvm/current/bin/pnpm
  npmPackages:
    @rspack/cli: latest => 0.4.5 
    @rspack/core: latest => 0.4.5
```

### Details

SwcCssMinimizerRspackPlugin changes `-160deg` to `200deg` etc., which causes wrong behavior

input
```css
.text {
    color: blue;
    background: conic-gradient(
        from -160deg at 50% 50%,
            #e92a67 0deg,
            #a853ba 120deg,
            #2a8af6 240deg,
            #e92a67 360deg
        );
}
```
wrong output(rspack+rspack.SwcCssMinimizerRspackPlugin)
```css
.text{color:blue;background:conic-gradient(from 200deg at 50%50%,#e92a67 0deg,#a853ba 120deg,#2a8af6 240deg,#e92a67 0deg)}
```
![WX20240103-153140@2x](https://github.com/web-infra-dev/rspack/assets/22063439/6500c7db-62ea-41e9-90a5-b16fb1a061e7)

output(webpack+CssMinimizerPlugin)
```css
.text{background:conic-gradient(from -160deg at 50% 50%,#e92a67 0deg,#a853ba 120deg,#2a8af6 240deg,#e92a67 1turn);color:blue}head{--webpack-rspack-repro-src_render_js:\.\/src\/render\.css}
```
![WX20240103-153107@2x](https://github.com/web-infra-dev/rspack/assets/22063439/ed0d11c6-e98f-4fa5-9b2b-e6ea10edc504)

### Reproduce link

https://github.com/guomio/rspack-issue-SwcCssMinimizerRspackPlugin

### Reproduce Steps

1. git clone https://github.com/guomio/rspack-issue-SwcCssMinimizerRspackPlugin
2. npm i
3. npm run build
4. see the output
