### ISSUE TITLE
[CSS Modules] export css modules varibles and sass `:export` variables for `css/module` type

### ISSUE THREAD

**Issue by xc2** [web-infra-dev/rspack#5454]
### What problem does this feature solve?

when building a "css/module" type setup, rspack doesn't export variables from css/sass as css-loader do.

## a full example:

https://github.com/xc2/rspack-repro-css-modules-var-export

### .scss

```scss
$scss-var: #f00;
@value css-module-var: #f00;

html {
  --css-var: #0f0;
}

:export {
  scss-var-in-export: #00f;
}

.foo {
  color: $scss-var;
}
```

### rspack exports

```js
{
  "foo": "foo__foo",
}
```

### css-loader exports

```js
{
	"css-module-var": `#f00`,
	"scss-var-in-export": `#00f`,
	"foo": `foo__foo`
}
```

## Full test result

```scss
/**
 * 1. native sass variable
 * css-loader: no
 * rspack css/module: no
 */
$scss-var: #f00;

/**
 * 2. css modules variables @{link https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md}
 * css-loader: yes
 * rspack css/module: no
 */
@value css-module-var: #f00;

html {
  /**
   * 3. native css variables
   * css-loader: no
   * rspack css/module: no
   */
  --css-var: #0f0;
}

:export {
  /**
   * 4. scss export
   * css-loader: yes
   * rspack css/module: no
   */
  scss-var-in-export: #00f;
}

/**
 * 5. css class name
 * css-loader: yes
 * rspack css/module: yes
 */
.foo {
  color: $scss-var;
}
```

### What does the proposed API of configuration look like?

export variables as css-loader do
