### ISSUE TITLE
CssExtractPlugin error: Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by JSerFeng** [web-infra-dev/rspack#6148]
reproduce:

```js
// index.js
import './test/index.module.css'
new URL('./foo.png', import.meta.url)
```

```css
body: { background: url('./foo.png') }
```

Error CssExtractPlugin error: Multiple assets emit different content to the same filename
