### ISSUE TITLE
[Bug]: CSS modules with SCSS syntax emits broken styles 

### ISSUE THREAD

**Issue by krutoo** [web-infra-dev/rspack#6687]
### System Info

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 22.27 GB / 31.21 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.2 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.112
  npmPackages:
    @rspack/cli: ^0.7.0 => 0.7.0 
    @rspack/core: ^0.7.0 => 0.7.0 

### Details

Here is an example of strange behavior of `css/module` generator:
https://github.com/krutoo/rspack-scss-modules

Maybe i am configure Rspack wrong but in styles there is somthing strange:

#### Input scss file
```scss
@use '../colors';
@use '../utils';
@use '../shadows';

.arrow-button {
  @include utils.focus-visible;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: #fff;
  border-radius: 50%;
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  box-sizing: border-box;
  transition: box-shadow 200ms ease-out;
  color: colors.$basic-gray87;
  &:not(:disabled):hover {
    cursor: pointer;
  }
  &:disabled {
    color: colors.$basic-gray24;
  }
  &.size-s {
    width: 32px;
    height: 32px;
    @include shadows.box-shadow('z2');
    &:not(:disabled):hover {
      @include shadows.box-shadow('z3');
    }
  }
  &.size-l {
    width: 56px;
    height: 56px;
    @include shadows.box-shadow('z3');
    &:not(:disabled):hover {
      @include shadows.box-shadow('z4');
    }
  }
}
```

### Output css file 

```css
.arrow-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: #fff;
  border-radius: 50%;
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  box-sizing: border-box;
  transition: box-shadow 200ms ease-out;
  color: #212121;
}
.__src_arrow-button_arrow-button_m_scss__arrow-button:focus-visible {
  outline: 2px solid #1f84db;
}
/* ... */
```

As you can see the first selector emits without modification but next selectors has modifications according to configuration of generator

### Reproduce link

https://github.com/krutoo/rspack-scss-modules

### Reproduce Steps

1. `npm i`
2. `npm run dev`
3. go to http://localhost:8080
4. see almost styled buttons
5. go to http://localhost:8080/index.css
6. see strange style output
