### ISSUE TITLE
[Bug]: CSS modules classNames that use composes breaks if the className is used again in the file

### ISSUE THREAD

**Issue by keyrun** [web-infra-dev/rspack#6761]
### System Info

 System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 29.40 GB / 63.95 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.2.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (125.0.2535.79)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rspack/cli: 0.7.1 => 0.7.1
    @rspack/core: 0.7.1 => 0.7.1
    @rspack/plugin-react-refresh: 0.7.1 => 0.7.1

### Details

Writing css modules with compose breaks if you use the className again after composes. 
```css
.columnCenter {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.root {
  composes: columnCenter;
  max-width: 1280px;
}
.root.main {
  background-color: #000;
  color: #fff;
}
```
This generates an export for root without the columnCenter className attached.
Rewriting it like this technically fixes it.
```css
.columnCenter {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.root.main {
  background-color: #000;
  color: #fff;
}
.root {
  composes: columnCenter;
  max-width: 1280px;
}
```
But ideally, the order of writing should not be an issue.

### Reproduce link

https://github.com/keyrun/rspack-cssmodule-issue/blob/main/rspack-dist/src_render_js.js

### Reproduce Steps

1. Run npm run build
2. In rspack-dist/src_render_js.js the root className should consist of both columnCenter and root but only contains root
