### ISSUE TITLE
[Bug]: Fonts are no longer bundld

### ISSUE THREAD

**Issue by kaisellgren** [web-infra-dev/rspack#7080]
### System Info

System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
    Memory: 39.17 GB / 61.94 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 125.0.6422.112

### Details

Everything worked in 0.6.5, but broke in 0.7.0, and is still broken in alpha-2 version.

Given the following CSS file contents:
```css
@font-face {
    font-family: Chevin;
    src: url(fonts/chevin-thin.woff2) format("woff2"), url(fonts/chevin-thin.woff) format("woff"), url(fonts/chevin-thin.ttf) format("truetype");
    font-weight: 100;
    font-style: normal
}
```

Asset defined:
```javascript
        {
          test: /\.(gif|png|jpe?g|svg|webp|ttf|woff|woff2|docx|pdf|crt|key)$/,
          type: 'asset/resource',
        },
```

Importing the CSS file via TypeScript code:

```typescript
import 'some.css'
```

The output folder does *not* include any of those font files from the CSS:

![image](https://github.com/web-infra-dev/rspack/assets/148256/74ee6584-d026-4ad9-a3fd-1c34192e4f35)

With the older 0.6.5 version or Webpack, the fonts appear correctly. Here's an example with Webpack:

![image](https://github.com/web-infra-dev/rspack/assets/148256/150807b8-7463-4ea3-8b68-adea3086b12e)

The compiled Rspack CSS file shows "file not found" error, because the fonts aren't copied to target folder:

![image](https://github.com/web-infra-dev/rspack/assets/148256/8f66e774-2bfc-40af-b996-8bfca24e0a4c)

I have not yet figured out how to make a simple repro case. When I create a simple case it works, but not in our codebase, but worked in 0.6.5 and works in Webpack.

Do you have suggestions what I could try to do?

**EDIT:** Looks like the fonts end up in `assets` folder instead:

![image](https://github.com/web-infra-dev/rspack/assets/148256/fdf4d50d-8c85-43e2-9d48-07fc3fb97a26)
