### ISSUE TITLE
[Bug]: Rspack ignores layers specified on imports in the main css file

### ISSUE THREAD

**Issue by dnwhte** [web-infra-dev/rspack#7452]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.32 GB / 15.92 GB
  Browsers:
    Chrome: 127.0.6533.89
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @rsbuild/core: ^1.0.1-beta.9 => 1.0.1-beta.9
    @rsbuild/plugin-react: ^1.0.1-beta.9 => 1.0.1-beta.9
```

### Details

The builtin:lightningcss-loader ignores layers specified on imports in the root css file. 

## Index.css
```css
@layer reset, base, components;

@import './a.css' layer(reset);
@import './b.css' layer(base);
```

## Expected Output
```css
@layer reset {
  .a {
    color: red;
  }
}

@layer base {
  .b {
    color: green;
  }
}

@layer components;

```

## Actual Output
```css
.a {
  color: red;
}

.b {
  color: green;
}

@layer reset, base, components;


```

### Reproduce link

https://codesandbox.io/p/devbox/9lyypl?migrateFrom=7rj2zn

### Reproduce Steps

1. Use the builtin:lightningcss-loader in your config
2. In the root css file import another css file and set a layer for it.  - `@import './component.css' layer(components)`
3. Run the rsbuild
4. Check of the components are properly layered in the output css
