### ISSUE TITLE
[Bug]: CSS output extra details about lang(*) dir(*)

### ISSUE THREAD

**Issue by 1yasa** [web-infra-dev/rspack#8405]
### System Info

System:
    OS: macOS 14.4
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900KF
    Memory: 6.79 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.8.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.9.0 - /usr/local/bin/pnpm
    bun: 1.1.24 - /usr/local/bin/bun
    Watchman: 2024.06.10.00 - /usr/local/bin/watchman

### Details

After update to rsapck version > 0.1.4 , build app then output css that has extra unnessary content:

![Image](https://github.com/user-attachments/assets/636326a6-46fb-43a6-b453-bb932a3e0188)

Here is the origin css:

```css
.__editor_block_special {
	padding-inline-start: 0;
	padding-inline-end: 0;
	margin-inline-start: var(--editor_padding_x);
	margin-inline-end: var(--editor_padding_x);
}
```

Tried custom LightningCssMinimizerRspackPlugin options:

```ts
optimization: {
	minimizer: [
		new LightningCssMinimizerRspackPlugin({
			minimizerOptions: {
				exclude: {
					langSelectorList: true,
					dirSelector: true
				}
			}
		})
	]
}
```

Still dir selector exsit:

![Image](https://github.com/user-attachments/assets/4941d2c5-b8fa-4c29-a951-9473143943c9)

Temp resolution is downgrading rspack version to 1.0.4 or set targets to `chrome >= 120`:

```ts
optimization: {
	minimizer: [
		new LightningCssMinimizerRspackPlugin({
			minimizerOptions: {
				targets: 'chrome >= 120'
			}
		})
	]
}
```

### Reproduce Steps

see above.
