### ISSUE TITLE
[Bug]: Rspack lightningcss-loader not supporting vue :deep()

### ISSUE THREAD

**Issue by lzxb** [web-infra-dev/rspack#8695]
### System Info

  System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1
    Memory: 98.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.11.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.15.0 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
    bun: 1.1.27 - ~/.bun/bin/bun
  Browsers:
    Safari: 18.1.1

### Details

```css
.faq-desc {
  background: red;
}
.faq-desc :deep(.ui-collapse)-item.expanded {
  border-bottom-width: 0;
}

.faq-desc :deep(.ui-collapse)-item-title {
  flex: 1;
  transition: all linear 0.4s;
}

.faq-desc :deep(.ui-collapse)-item-header {
  border: none;
  padding: 20px 0;
  font-size: 16px;
  font-weight: 500;
  height: auto;
  align-items: flex-start;
}

.faq-desc :deep(.ui-collapse)-item-header:hover .fmui-collapse-item-title {
  transform: translate(8px);
}

.faq-desc :deep(.ui-collapse)-item-content {
  padding: 0;
  font-size: 14px;
  font-weight: 400;
}

.faq-desc :deep(.ui-collapse)-item-content>div {
  margin-bottom: 20px;
  padding-top: 10px;
}
```

Vue component CSS, lost after `builtin:lightningcss-loader ` processing
<img width="506" alt="Image" src="https://github.com/user-attachments/assets/3dc9b3dd-26ed-43bf-8ff4-53c76d70f517" />

### Reproduce link

https://github.com/lzxb/rspack-vue-deep-error

### Reproduce Steps

pnpm i
pnpm build
