### ISSUE TITLE
[Feature]: Support `publicPath: auto` in asset module

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rspack#8748]
### What problem does this feature solve?

https://github.com/SoonIter/rspack-asset-module-publicPath-auto

#### input

```ts
// src/index.ts
import x from './assets/react.svg';
```

#### expected output
rspack-dist/index.js
rspack-dist/static/svg/react.svg

```js
module.exports = "./static/svg/react.svg";
```

#### actual output

rspack-dist/index.js
rspack-dist/static/svg/react.svg

```js
module.exports = "../../static/svg/react.svg";
```

😭 the auto public path is based on `static/svg/react.svg` not `index.js`

#### webpack output

```
module.exports = "autostatic/svg/react.svg";
```

😂 This feature is not supported in Webpack  currently

### What does the proposed API of configuration look like?

```
module: {
    generator: {
      asset: {
        publicPath: 'auto'
      }
    },
    rules: [
      {
        test: /\.svg$/,
        type: 'asset',
      },
    ]
}
```

**Comment by SoonIter** [comment]
need enforce relative to support lib css output

#### Input

```css
// index.css
.a {
  background: url('./assets/react.svg');
}

```

#### `experimental: css` output

```css
.a {
  background: url(/static/svg/react.svg);
}
```

#### `css-extract-rspack-plugin`

```css
.a {
  background: url(/static/svg/react.svg);
}
```
