### ISSUE TITLE
[Bug]: Compilation hangs when double slashes exist in filename

### ISSUE THREAD

**Issue by matthiask** [web-infra-dev/rspack#8961]
### System Info

  System:
    OS: Linux 6.12 Fedora Linux 41 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1130G7 @ 1.10GHz
    Memory: 5.75 GB / 15.34 GB
    Container: Yes
    Shell: 5.2.32 - /bin/bash
  Binaries:
    Node: 22.11.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.9.0 - /usr/bin/npm
  npmPackages:
    @rspack/cli: ^1.1.8 => 1.1.8 
    @rspack/core: ^1.1.8 => 1.1.8 

### Details

First let me say thanks for rspack, it's great.

I have found a strange error where compilation hangs when an URL contains a double slash:

```css
@font-face {
  font-family: "Source Sans 3 var";
  font-style: normal;
  font-weight: 200 900;
  font-display: swap;
  font-style: normal;
  font-named-instance: "Regular";
  /* This works: *
  src: url("../fonts/SourceSans3-Regular.woff2") format("woff2");
  /* This hangs: */
  src: url("../fonts//SourceSans3-Regular.woff2") format("woff2");
}
```

The double slash shouldn't be there, and everything works fine if it isn't. If it's there, rspack hangs while idle (no CPU spikes)

### Reproduce link

https://github.com/matthiask/double-slash-hang

### Reproduce Steps

1. Clone repo
2.  `npx pnpm i`
3. `npx pnpm run build:rspack`

Observe how the error disappears when using the line without the double slash.
