### ISSUE TITLE
[Bug]: Rspack automatically completes unit-less values when processing CSS minification using LightningCssMinimizerRspackPlugin

### ISSUE THREAD

**Issue by xierenyuan** [web-infra-dev/rspack#9567]
### System Info

  System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 147.05 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: 8.7.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
    Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 133.0.6943.142
    Safari: 16.5
  npmPackages:
    @rspack/cli: ^1.2.7 => 1.2.7 
    @rspack/core: ^1.2.7 => 1.2.7 
    @rspack/plugin-react-refresh: ^1.0.1 => 1.0.1 

### Details

```css
.css-no-vaild {
  width: 100;
  height: 100px;
  background-color: red;
}
```
mini

```css
.css-no-vaild{background-color:red;width:100px;height:100px}
```
Webpack does not process this and we expect to restore the default behavior, which is very important for migrating legacy projects

![Image](https://github.com/user-attachments/assets/83361267-7e12-49f1-b286-e07ad3bd95c2)

### Reproduce Steps

[rspack-css.zip](https://github.com/user-attachments/files/19092448/rspack-css.zip)
pnpm install
pnpm build
