### ISSUE TITLE
[Bug]: alias not work for CSS @import

### ISSUE THREAD

**Issue by ckken** [web-infra-dev/rspack#9771]
### System Info

 System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 553.82 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 8.15.5 - ~/Library/pnpm/pnpm
    bun: 1.2.5 - ~/.bun/bin/bun
    Watchman: 2024.10.14.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 134.0.6998.118
    Safari: 17.6

### Details

# style.css 
## 生效
```css
@import "/path/tailwindcss@4.0.15/node_modules/tailwindcss";

@layer components {
	.DocSearch-Hit--Result {
		background-color: --alpha(var(--color-gray-950) / 10%);
	}
}
```
## 无效
```css
@import "tailwindcss";

@layer components {
	.DocSearch-Hit--Result {
		background-color: --alpha(var(--color-gray-950) / 10%);
	}
}
```
index.js
## 有效
```js
import 'tailwindcss' 
```

# 路径设置代码  
```js
 //
      const tailwindcssPath = require.resolve('tailwindcss')
      const installDir = path.dirname(path.dirname(tailwindcssPath))
      //
      chain.module
        .rule(store.chainName.rule.css)
        .set('type', 'css')
        .use('postcss')
        .loader(require.resolve('postcss-loader'))
        .options({
          postcssOptions: {
            plugins: {
              '@tailwindcss/postcss': {},
            },
          },
        })
      //
      chain.resolve.alias.set('tailwindcss', installDir)
```

### Reproduce Steps

Error: Can't resolve 'tailwindcss'
