### ISSUE TITLE
[Bug]: pass wrong css to lightingcss-loader without any warning but loader will remove the code

### ISSUE THREAD

**Issue by SyMind** [web-infra-dev/rspack#9896]
### System Info

-

### Details

```css
@media screen and (max-width: 1440px) {
    .k-common-quick-access-item {
      margin-right: 12px;
      margin-bottom: 12px;
      width: calc((100% - 24px) / 3);

      &:nth-child(6n - 1) {
        margin-right: 0px;
      }
    }
  }

  @media screen and (min-width: 1440px) and(max-width: 1920px) {
    .k-common-quick-access-item {
      margin-right: 12px;
      margin-bottom: 12px;
      width: calc((100% - 36px) / 4);

      &:nth-child(8n - 1) {
        margin-right: 0px;
      }
    }
  }

  @media screen and (min-width: 1920px) {
    .k-common-quick-access-item {
      margin-right: 12px;
      margin-bottom: 12px;
      width: calc((100% - 48px) / 5);

      &:nth-child(10n - 1) {
        margin-right: 0px;
      }
    }
  }
```

### Reproduce Steps

-
